---

- name: Check if using Nvidia Graphics card
  shell: "lshw -c display | grep -q 'vendor: NVIDIA Corporation'"
  register: nvidia_graphics
  changed_when: false
  tags:
    - baseline
    - desktop
    - nvidia

- name: Include Nvidia config
  include_tasks: nvidia.yaml
  when:
    - nvidia_graphics.rc == 0
  tags:
    - baseline
    - desktop
    - nvidia

- name: Include Gnome config
  include_tasks: gnome.yaml
  tags:
    - baseline
    - desktop
    - gnome

- name: Include user config
  include_tasks: user.yaml
  tags:
    - baseline
    - desktop
    - user

- name: Include gdm3 config
  include_tasks: gdm3.yaml
  tags:
    - baseline
    - desktop
    - gdm3

- name: Include package installation
  include_tasks: packages.yaml
  tags:
    - baseline
    - desktop

- name: Include network config
  include_tasks: networking.yaml
  tags:
    - baseline
    - desktop
    - networking
