---
- name: Configure Nvidia graphics
  block:

  - name: Check if prime-select available
    stat:
      path: /usr/bin/prime-select
    register: prime_select

  - name: Get current Nvidia Prime profile
    shell:
      cmd: prime-select query
    register: prime_profile
    changed_when: false
    when: prime_select.stat.executable

  # prime-select on-demand
  - name: Set Nvidia Prime profile to On-Demand
    command:
      cmd: prime-select on-demand
    become: yes
    when:
      - prime_select.stat.executable
      - prime_profile.stdout != "on-demand"

  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == ubuntu_version
  tags:
    - baseline
    - desktop
    - nvidia
