- name: Configure Python environment
  block:

  - name: Install baseline packages for my desktop
    apt:
      name: "{{ package }}"
      state: latest
    loop:
      - dconf-editor
      - sensors-applet
      - zfsutils-linux
      - vim
      - tree
      - mutt
      - curl
      - wget
      - htop
      - evolution
      - evolution-ews
    loop_control:
      loop_var: package
    become: yes

  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == ubuntu_version
  tags:
    - baseline
    - desktop
