- name: Configure software environment
  block:

  - name: Install Common packages
    apt:
      name: "{{ package }}"
      state: latest
    loop:
      - build-essential
      - libssl-dev
      - libffi-dev
    loop_control:
      loop_var: package
    become: yes
    tags:
      - always

  - name: Install Python packages
    apt:
      name: "{{ package }}"
      state: latest
    loop:
      - python
      - python-dev
      - python-netaddr
      - python-psutil
    loop_control:
      loop_var: package
    become: yes

  - name: Install Python3 packages
    apt:
      name: "{{ package }}"
      state: latest
    loop:
      - python3
      - python3-dev
      - python3-netaddr
      - python3-venv
      - python3-psutil
    loop_control:
      loop_var: package
    become: yes
    tags:
      - python3

  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == ubuntu_version
  tags:
    - python
